language: node_js
node_js:
- 12.16
script: true
deploy:
  provider: heroku
  api_key:
    secure: jwu7ODY3nOhfMJyZstyngeo6hb2gIWyKzOzi1EzZbv4YSHHs4egTNHzUB4nsCr73DQIe2Mbu2DjYCaSJAp75eEbwUWbtpWbcObUHSYE9s6SBRaqs7OXxB6RRxj6oZM3tMqUMj+T3NnYe4DpxABARW5XfpSmEIvMM39X3kkusilcVgPPNcWhlq4onKAAy+LOeeaIpoJtqHzDgCac/0jDlLwlKkgR5OAGrOPGrHjBLdYCvffgKhSfewqRhuV05bVPbtxSCWpSAz5LqLkK7/z31ACkQqUHHPGPQqHgEWzPXB9oExAT+Z9jcovVFulaHrQV8Plpr3EFibmrLr08jI4WFC/yvQ9YyuafQp+rnUrEsafVwE7YKlqGFZCA9UEY64RyfkhGgHHYrnXYaG497C4XmOWOKkE4+rTL/LNAqSeQ1Tv+GHzucOlW2ENKgyXcZJH1xoEUiZpLUlW4SIdpqEAO+8WUOPmExH5IjWc+FI6SQTsRIFBvWPZO7MMZgO16FP7L1v4Ckjz35nH4cHYV6cyr3C2FwIyEX9mSYxxL/eZFDKbpmGWpayxzOHCxVv6kiub5IPsIscHoidb7zlrirrGkC/kvjgDUnKy+BR8MuICDbBpvYho9Yn9arHWx/6XiJO92tsKLavooRdpC+aYteL/mmixXNF+IpJQdheuFf4uiSn2E=
  app: progressive-web-apps-1920
  on:
    repo: tnanhekhan/progressive-web-apps-1920
