language: node_js
node_js:
- 12.16
script: true
deploy:
  provider: heroku
  api_key:
    secure: R2XYYivYIlCruYjLEPg04XYpfxWSz6exsjISwwRu/ysvV/ZKelABygaTf21etqmiZo+g+udLYy9KyImGVOvM1czah9gu/i7GhuHtt0Nv+raJuAJc7J0E1WbIBst3MBaWUXtb30BMx33gZoQbM6e6I/acn1ygWyZyroQOFNNlcb7gZ287/9XI+H/qlewaRX2fNQfUXYaUV7RzsH4dWMLhefTAAlIfm0mSaJc0vyt0Y2gN8B4EJG7tEr7OW/JpwdbtDc1yDn/MXic3Xg7HqVhS0g6RRYjH1/JZEanXpvrEYnzGWfnC+Kz+T1OkjvJszWi1h9paPvuRxdHMEWfrTOijdvi0CguYTF3noDQe0ez328fWziAJMlDZgNn940ZbcNJDNmW8jUTYvTcQSoFwnq3BPz8GQprJNIb9VFdF7TV440jOrKz6sIRwheS/7pDXe+H4OQrTVh3EcvB4NHix+xZK0bMqZV/onDa4U23tWZGpNyNBZKQE2IrwM6f/227muCPyaXIk8WKVVFqPbgR85MaM1HN2rXgbrjE5/Wk5Wdrb95CaL523slWTqoVuqcaVRMnwivVZoNGid4Qoys8Ez3ByK6lmmeIR+v2acRbccHe9JugBaNS/AY8R1NHJjXiLK0ja00HBmpfMBjSG6SJKy4aCSeOpvMulTzZKqZjrmDZOQns=
  app: progressive-web-apps-1920
  on:
    repo: tnanhekhan/progressive-web-apps-1920
